### ISSUE TITLE
ProjectsClient.create_project return object (google.api_core.operation.Operation.result) returns 404

### ISSUE THREAD

**Issue by nicain** [googleapis/python-resource-manager#109] opened 2021-09-01 19:00 UTC
- OS type and version:
  - Python version: Python 3.9.2
  - pip version: pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)
  - `google-cloud-resource-manager` version: 
  ```
Name: google-cloud-resource-manager
Version: 1.1.0
Summary: Google Cloud Resource Manager API client library
Home-page: https://github.com/googleapis/python-resource-manager
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /usr/local/google/home/nicholascain/.local/lib/python3.9/site-packages
Requires: packaging, grpc-google-iam-v1, proto-plus, google-api-core
Required-by:
```

#### Code example

```python
from google.cloud import resourcemanager
import google.auth
import os
os.environ.pop('GOOGLE_APPLICATION_CREDENTIALS', None)

PROJECT_ID = 'cloud-agent-tmp-3'
ORGANIZATION_ID = 298490623289

credentials, project_id = google.auth.default()
c = resourcemanager.ProjectsClient(credentials=credentials)
response = c.create_project(project=resourcemanager.Project(project_id=PROJECT_ID, parent=f'organizations/{ORGANIZATION_ID}'))
response.result()
```

#### Stack trace
```
Traceback (most recent call last):
  File "/usr/local/google/home/nicholascain/.local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 67, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/google/home/nicholascain/.local/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/google/home/nicholascain/.local/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = "Received http2 header with status: 404"
        debug_error_string = "{"created":"@1630522551.543701129","description":"Received http2 :status header with non-200 OK status","file":"src/core/ext/filters/http/client/http_client_filter.cc","file_line":132,"grpc_message":"Received http2 header with status: 404","grpc_status":12,"value":"404"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/google/home/nicholascain/projects/cloud_agent/create_project.py", line 12, in <module>
    response.result()
  File "/usr/local/google/home/nicholascain/.local/lib/python3.9/site-packages/google/api_core/future/polling.py", line 129, in result
    self._blocking_poll(timeout=timeout, **kwargs)
  File "/usr/local/google/home/nicholascain/.local/lib/python3.9/site-packages/google/api_core/future/polling.py", line 107, in _blocking_poll
    retry_(self._done_or_raise)(**kwargs)
  File "/usr/local/google/home/nicholascain/.local/lib/python3.9/site-packages/google/api_core/retry.py", line 285, in retry_wrapped_func
    return retry_target(
  File "/usr/local/google/home/nicholascain/.local/lib/python3.9/site-packages/google/api_core/retry.py", line 188, in retry_target
    return target()
  File "/usr/local/google/home/nicholascain/.local/lib/python3.9/site-packages/google/api_core/future/polling.py", line 85, in _done_or_raise
    if not self.done(**kwargs):
  File "/usr/local/google/home/nicholascain/.local/lib/python3.9/site-packages/google/api_core/operation.py", line 170, in done
    self._refresh_and_update(retry)
  File "/usr/local/google/home/nicholascain/.local/lib/python3.9/site-packages/google/api_core/operation.py", line 158, in _refresh_and_update
    self._operation = self._refresh(retry=retry)
  File "/usr/local/google/home/nicholascain/.local/lib/python3.9/site-packages/google/api_core/operations_v1/operations_client.py", line 142, in get_operation
    return self._get_operation(request, retry=retry, timeout=timeout, metadata=metadata)
  File "/usr/local/google/home/nicholascain/.local/lib/python3.9/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/google/home/nicholascain/.local/lib/python3.9/site-packages/google/api_core/retry.py", line 285, in retry_wrapped_func
    return retry_target(
  File "/usr/local/google/home/nicholascain/.local/lib/python3.9/site-packages/google/api_core/retry.py", line 188, in retry_target
    return target()
  File "/usr/local/google/home/nicholascain/.local/lib/python3.9/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/google/home/nicholascain/.local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 69, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.MethodNotImplemented: 501 Received http2 header with status: 404
```

**Comment by busunkim96** [comment] 2021-09-03 15:49
Thank you for reporting @nicain! I'm trying to reproduce this and am running into trouble with not having enough permission on orgs. Is there a particular org you used?

**Comment by busunkim96** [comment] 2021-09-07 22:51
Googlers, see the internal copy of this issue (198467677) for more details. 

This is either (1) an issue with how the backend API implemented LRO or (2) A bug in the Python generator, so I have marked it 'external'.

Also, the operations _do_ appear to complete (i.e., project is created) so I've marked as P2.

**Comment by ttruong-a10** [comment] 2021-09-09 21:33
I'm also running into this exact issue. Calling `operation.result() or operation.done()` will give 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/google/api_core/grpc_helpers.py", line 66, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNIMPLEMENTED
        details = "Received http2 header with status: 404"
        debug_error_string = "{"created":"@1631220415.287284200","description":"Received http2 :status header with non-200 OK status","file":"src/core/ext/filters/http/client/http_client_filter.cc","file_line":132,"grpc_message":"Received http2 header with status: 404","grpc_status":12,"value":"404"}"
```

**Comment by busunkim96** [comment] 2021-11-09 15:47
Googlers, see 199203237 for the issue filed against the Resource Manager API team.

**Comment by socketbox** [comment] 2021-12-03 04:51
@nicain How did you know to pass in the parent parameter value as a string formatted as 'organizations/{ORGANIZATION_ID}`?

**Comment by jsnod** [comment] 2022-01-19 20:59
This is hitting us too, we are unable to wait for project creation to complete before modifying policies or creating service accounts. @busunkim96 can you provide any insight on the "internal" issue number you posted above? Is it being worked on? Is there an ETA?

In the meantime, `time.sleep()` it is I guess... 🤷‍♂️

**Comment by busunkim96** [comment] 2022-01-19 22:31
Hi folks,

Apologies for the delay, we recognize being unable to poll the operation makes it very difficult to effectively use `create_project`. @jsnod The API team identified the cause about a week ago and seem to be in the middle of rolling out a fix. I've asked if they have a more specificETA I can share with you folks.

**Comment by busunkim96** [comment] 2022-02-08 18:50
The fix is now fully rolled out and I checked that this works for me in my own project. Please let us know if you are still seeing issues!

**Closed by busunkim96** 2022-02-08 18:50 UTC
Labels: api: cloudresourcemanager, type: bug, priority: p2, external
