### ISSUE TITLE
Access to Resource Manager's Organization Policies API (v1)

### ISSUE THREAD

**Issue by aderuelle** [googleapis/python-resource-manager#103] opened 2021-08-28 16:45 UTC
## Problem

I'd like to use the v1 API that relates to Organization Policy management with the Python client, but:

- Cloud Resource Manager v3 API does not provide access to the Organization Policy management 
- current version (1.1.0) of the `python-resource-manager` client does not provide wrappers around the v1 API which would expose the desired APIs [1]

## Question

I'd like to have guidance on the matter:

- would the v1 API be baked into the python-resource-manager client someday ?
- might other APIs / Python client give access to similar API
- are those APIs designed to only be accessed by other means (through discovery[2] for example)
- should I use older version of the `python-resource-manager`

Thank you,

Alexis

[1] https://cloud.google.com/resource-manager/reference/rest/v1/projects/getOrgPolicy
[2] https://cloud.google.com/resource-manager/reference/rest/v1/projects/getOrgPolicy#python

**Comment by busunkim96** [comment] 2021-08-30 20:12
Hi @aderuelle,

I believe resource manager v3 was intended to merge the features in v1 and v2. However, I see that the v3 doesn't seem to have org policy methods. I've opened a ticket with the internal teams that manage the Resource Manager and Organization Policy APIs and will update this issue once I get a response.

**Comment by parthea** [comment] 2023-04-15 13:39
I found an existing feature request for the API team [here](https://issuetracker.google.com/issues/128973398) to expand the V3 API to include features that were available in V1. Please visit this link to file additional feature [requests](https://issuetracker.google.com/issues/new?component=187210&template=0). I'm going to close this issue as it is a feature request for the API rather than the client library.

**Closed by parthea** 2023-04-15 13:39 UTC
Labels: api: cloudresourcemanager, type: question
